### ISSUE TITLE
What happens to the CONDITION TARGET?

### ISSUE THREAD

**Issue by mabra** [infinet/xtables-addons#1]
Hello!
Setting up a new firewall, got one of the last firewall scripts from my
repository, but fall onto my nose:

` .... -j CONDITION --condition ssh-log`
`iptables v1.8.9 (nf_tables): unknown option "--condition"`

Has this been an accident or has this TARGET really been removed?
If I omit the "--condition" qualifier, I am getting: "Bad argument 'ssh-log'
Are there probably other methods to write to '/proc/net/nf_condition/xxx'
which I dont have regarded?

**Comment by infinet** [comment]
This is a fork of xtables-addons. Perhaps you can ask the official repo?

**Comment by mabra** [comment]
Oh -- thanks, will try to find it!
